fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    chocolatey: "https://github.com/puppetlabs/puppetlabs-chocolatey.git"
    powershell: "https://github.com/puppetlabs/puppetlabs-powershell.git"
    registry: "https://github.com/puppetlabs/puppetlabs-registry.git"
    vcsrepo: "https://github.com/puppetlabs/puppetlabs-vcsrepo.git"
  symlinks:
    software: "#{source_dir}"
