# RuboCop config file
# Configure cops
# https://github.com/bbatsov/rubocop
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# https://github.com/bbatsov/ruby-style-guide
#

AllCops:
  Include:
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Guardfile'
  Exclude:
    - 'pkg/**/*'
  RunRailsCops: false
  DisplayCopNames: true

Metrics/MethodLength:
  # Ruduce this... Max: 10
  Max: 28

Metrics/LineLength:
  # Ruduce this... Max: 80
  Max: 100

Metrics/AbcSize:
  # Ruduce this... Max: 15
  Max: 30

Metrics/CyclomaticComplexity:
  # Ruduce this... Max: 6
  Max: 8

# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles.
# Support ruby 1.8.7
Style/HashSyntax:
  EnforcedStyle: hash_rockets
