---
language: ruby

install:
  - wget 'https://pm.puppetlabs.com/cgi-bin/pdk_download.cgi?dist=ubuntu&rel=16.04&arch=amd64&ver=latest' -q -O pdk.deb && sudo dpkg -i pdk.deb && rm pdk.deb

stages:
  - validate
  - test

jobs:
  include:
    - stage: validate
      script: pdk validate 2> /dev/null

    - stage: test
      script: pdk test unit 2> /dev/null
